import itertools
import logging
from decimal import Decimal
from typing import Iterator

from defabipedia import Chain
from karpatkit.cache import cache_contract_method
from karpatkit.helpers import listify, suppress_value
from web3 import Web3
from web3.exceptions import ContractCustomError, ContractLogicError

from defyes.types import Token, TokenAmount

from .autogenerated import BancorPool, BancorNetwork, BancorNetworkInfo

logger = logging.getLogger(__name__)


class BancorNetwork(BancorNetwork):
    pass


class BancorNetworkInfo(BancorNetworkInfo):
    pass


class BancorPool(BancorPool):
    pass